### ISSUE TITLE
最近渲染水印图为什么一天之后还是在现实任务排队中

### ISSUE THREAD

**Issue by tongyiwen** [xuanran001/xuanran001.com#6]
最近渲染水印图为什么一天之后还是在现实任务排队中

**Comment by xxd3vin** [comment]
Please provide camera name for this render job

e.g. 3空间九龙花园小区主卧(pm104)

**Comment by tongyiwen** [comment]
儿童房（91065）
3（667g)
卧室（g2il)

**Comment by xxd3vin** [comment]
Problem solved, please check it.

**Comment by tongyiwen** [comment]
显示  渲染完成,图像后续处理中,请稍后在 "已完成" 中查看结果，但是已完成中没有图片

**Comment by xxd3vin** [comment]
请重新提交渲染任务。

```
"retry": "5"
```

**Comment by xxd3vin** [comment]
有一台渲染机出问题了，所以有些render job会被重新调度。

已经撤下了出问题的渲染机。
